------------------------------------------------------------
RP_SILVER_DB_PROD
------------------------------------------------------------

RP_SILVER_DB_PROD.DES_PROD.ORDERS_CO
RP_SILVER_DB_PROD.DES_PROD.ORDERS_PE
RP_SILVER_DB_PROD.DES_PROD.ORDERS_GMV_CO
RP_SILVER_DB_PROD.DES_PROD.ORDER_TIMES_CO
RP_SILVER_DB_PROD.DES_PROD.CANCELLATIONS_CO
RP_SILVER_DB_PROD.DES_PROD.CANCELLATIONS_VARIABLES_CO
RP_SILVER_DB_PROD.DES_PROD.BAD_ORDERS
RP_SILVER_DB_PROD.DES_PROD.ORDER_PRODUCTS_CO
RP_SILVER_DB_PROD.DES_PROD.RTS_CO
RP_SILVER_DB_PROD.DES_PROD.STORES_CO
RP_SILVER_DB_PROD.DES_PROD.MICROZONES_CO

RP_SILVER_DB_PROD.CPGS_LOCAL_ANALYTICS.TBL_DIM_STORES
RP_SILVER_DB_PROD.CPGS_LOCAL_ANALYTICS.TBL_RETAILER_PRODUCT_CP
RP_SILVER_DB_PROD.CPGS_LOCAL_ANALYTICS.TBL_TIPIFICADOR_CO
RP_SILVER_DB_PROD.CPGS_LOCAL_ANALYTICS.TBL_MASTER_ORDERS_GENERAL
RP_SILVER_DB_PROD.CPGS_LOCAL_ANALYTICS.TBL_PERFECT_STORES_RETAIL

RP_SILVER_DB_PROD.OPS_CPGS_NOW.REGION_ANDINA_CANCELACIONES_DAILY
RP_SILVER_DB_PROD.OPS_CPGS_NOW.MSA_OPS_RETAIL_BB_SAVINGS_REVIEW_RAW_DATA_TBL
RP_SILVER_DB_PROD.OPS_CPGS_NOW.PASCOABR26
RP_SILVER_DB_PROD.OPS_CPGS_NOW.DEFECT_ORDER_PRODUCTS_RETAIL_PBI_TB
RP_SILVER_DB_PROD.OPS_CPGS_NOW.VIL_BOT


------------------------------------------------------------
RP_GOLD_DB_PROD
------------------------------------------------------------

RP_GOLD_DB_PROD.DES_PROD.ORDER_DIMENSIONS_CO
RP_GOLD_DB_PROD.DES_PROD.ORDER_DIMENSIONS

RP_GOLD_DB_PROD.FUL_CORE_DS.ASSIGN_ITERATIONS
RP_GOLD_DB_PROD.FUL_CORE_DS.CNS_EARNINGS_CALCULATED_INFORMATION
RP_GOLD_DB_PROD.FUL_CORE_DS.STOREKEEPER_LEVEL_HISTORY

RP_GOLD_DB_PROD.FUL_ANALYTICS.TBL_HISTORY_LEVELS
RP_GOLD_DB_PROD.FUL_FORECASTING.GLOBAL_COURIER_PRODUCTIVITY_VW
RP_GOLD_DB_PROD.FUL_JET.SCHEDULING_PROVIDER_PIVOTS

RP_GOLD_DB_PROD.UE.PNL


------------------------------------------------------------
FIVETRAN
------------------------------------------------------------
 FIVETRAN.CPGS_OPS_CPGS_COL.ORDENES_HISTORICAS_OCT2021_DIC072024 ---> Tabla histórica con ordenes de Retail Colombia

FIVETRAN.CO_CORE_ORDERS_PUBLIC.ORDER_MODIFICATIONS

FIVETRAN.CO_PG_MS_CPGOPS_STORES_MS_PUBLIC.SLOT_CONFIGS_PHYSICAL_STORES
FIVETRAN.CO_PG_MS_CPGOPS_STORES_MS_PUBLIC.PHYSICAL_STORES
FIVETRAN.CO_PG_MS_CPGOPS_STORES_MS_PUBLIC.APP_CONFIGS_PHYSICAL_STORES

FIVETRAN.CO_AMYSQL_CPGS_CLG_IM_CPGS_CLG_INVENTORY_MANAGER.PRODUCT
FIVETRAN.CO_AMYSQL_CPGS_CLG_IM_CPGS_CLG_INVENTORY_MANAGER.STORE
FIVETRAN.CO_AMYSQL_CPGS_CLG_IM_CPGS_CLG_INVENTORY_MANAGER.VIRTUAL_STORE
FIVETRAN.CO_AMYSQL_CPGS_CLG_IM_CPGS_CLG_INVENTORY_MANAGER.RETAILER
FIVETRAN.CO_AMYSQL_CPGS_CLG_IM_CPGS_CLG_INVENTORY_MANAGER.PRODUCT_AVAILABILITY
FIVETRAN.CO_AMYSQL_CPGS_CLG_IM_CPGS_CLG_INVENTORY_MANAGER.COMPLEX_DISCOUNT
FIVETRAN.CO_AMYSQL_CPGS_CLG_IM_CPGS_CLG_INVENTORY_MANAGER.VIRTUAL_PRODUCT

FIVETRAN.CO_PG_MS_ASSIGN_MONITORING_PUBLIC.ORDERS
FIVETRAN.CO_PG_MS_ASSIGN_MONITORING_PUBLIC.COURIERS
FIVETRAN.CO_PG_MS_ASSIGN_MONITORING_PUBLIC.ROUTES

FIVETRAN.CO_PGLR_MS_STORES_PUBLIC.STORES_VW

FIVETRAN.CO_PG_MS_CMS_STORES_CONFIG_PUBLIC.BRAND_GROUPS
FIVETRAN.CO_PGLR_MS_CMS_STORES_CONFIG_PUBLIC.STORE_SPINOFF

FIVETRAN.CO_PGN_MS_FTC_SLOTS_MS_PUBLIC.BLENDED_STORES

FIVETRAN.CO_PGLR_MS_COUNTRY_DATA_PUBLIC.CITY_ADDRESSES_VW

FIVETRAN.CO_PG_MS_CNS_PICKING_MS_PUBLIC.ORDER_PRODUCTS
FIVETRAN.CO_PG_MS_CNS_PICKING_MS_PUBLIC.SCANNER_EVENT

FIVETRAN.CO_PG_MS_KUSTOMER_ETL_PUBLIC.BAD_ORDER_PRODUCTS

FIVETRAN.CO_PG_MS_CPGOPS_POS_API_MS_PUBLIC.TRANSACTIONS
FIVETRAN.CO_PG_MS_CPGOPS_POS_API_MS_PUBLIC.ORDERS
FIVETRAN.CO_PG_MS_CPGOPS_POS_API_MS_PUBLIC.TRANSACTION_BASKETS

FIVETRAN.CPG_INTEGRATIONS.CO_NEW_CATALOG_INTEGRATION_METRICS_METADATA
FIVETRAN.CPG_INTEGRATIONS.OVERRIDE_AVAILABILITY

FIVETRAN.CPGS_DATASCIENCE.DM_SWA_THEORETICAL_VS

FIVETRAN.CPGS_SALESCAPABILITY.TBL_CORE_PRODUCTS_IDEAL_BASKET_BY_STORE_CP
FIVETRAN.CPGS_SALESCAPABILITY.VW_CONDOR_ETA_SCHEDULED_STORE_TYPE
FIVETRAN.CPGS_SALESCAPABILITY.TBL_CONDOR_ETA_RAW_DATA

FIVETRAN.VERTICALS_LATAM.CO_VERTICALS_V2


------------------------------------------------------------
OTRAS / CROSS-SCHEMA
------------------------------------------------------------

FIVETRAN.GLOBAL_FINANCES.TRM_FIXED
FIVETRAN.GLOBAL_CONVERSIONS.GLOBAL_CONVERSIONS

FIVETRAN.CS_CORE.BAD_ITEMS
FIVETRAN.CS_CORE.DEFECTS_COMPENSATED

FIVETRAN.SK_PAYMENT_METHOD.PAYMENT_TRANSACTIONS

FIVETRAN.CPGS_OPS_CPGS_COL.PRUEBA_EXITO
FIVETRAN.CPGS_OPS_CPGS_COL.AGUAS_BOGOTA
FIVETRAN.CPGS_OPS_CPGS_COL.DUMMY_TABLE_SS_VS_INT


------------------------------------------------------------
NOTAS
------------------------------------------------------------

- Prefijo [XX]_ en tablas de Picking y otras = swap de pais:
  CO_ / BR_ / PE_ / EC_ / CR_ segun el pais analizado

- TBL_DIM_STORES en CPGS_LOCAL_ANALYTICS reemplaza a
  la version anterior en FIVETRAN.CPGS_SALESCAPABILITY

- REGION_ANDINA_CANCELACIONES_DAILY: una fila por orden,
  usar COUNT(DISTINCT IFF(is_cancelled=TRUE AND
  effective_repurchase=FALSE, order_id, NULL)) para CR real

- ORDER_DIMENSIONS_CO esta en RP_GOLD_DB_PROD.DES_PROD,
  NO en Silver

- ASSIGN_ITERATIONS esta en RP_GOLD_DB_PROD.FUL_CORE_DS

============================================================